{% set name = "dask-jobqueue" %}
{% set version = "0.6.0" %}
{% set sha256 = "296b91c1d4a1aec7ab21d97e001fc394401b978f340f250aedda1fd60350bfef" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python>=3.5
    - dask>=1.2.0
    - distributed>=1.27
    - docrep

test:
  imports:
    - dask_jobqueue

about:
  home: https://github.com/dask/dask-jobqueue
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Easy deployment of Dask Distributed on job queuing systems like PBS, Slurm, LSF and SGE.'
  description: |
    Easy deployment of Dask Distributed on job queuing systems such as PBS,
    Slurm, LSF or SGE.
  doc_url: https://jobqueue.dask.org
  dev_url: https://github.com/dask/dask-jobqueue

extra:
  recipe-maintainers:
    - jhamman
    - mrocklin
    - lesteve
    - guillaumeeb
