{% set name = "dask-jobqueue" %}
{% set version = "0.5.0" %}
{% set sha256 = "b3cd21de2786bef9d863a8a09b60761ce7c408890caf9274799b8d5edaa7675a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - dask>=0.18.1
    - distributed>=1.22
    - docrep

test:
  imports:
    - dask_jobqueue

about:
  home: https://github.com/dask/dask-jobqueue
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Easy deployment of Dask Distributed on job queuing systems like PBS, Slurm, and SGE.'
  description: |
    Easy deployment of Dask Distributed on job queuing systems such as PBS,
    Slurm, or SGE.
  doc_url: https://dask-jobqueue.readthedocs.io
  dev_url: https://github.com/dask/dask-jobqueue

extra:
  recipe-maintainers:
    - jhamman
    - mrocklin
    - lesteve
    - guillaumeeb
