travis:
  secure:
    BINSTAR_TOKEN: DSTa9ikIUxgX512fCWBZqYZZphlmUr4FK+3kHhbFq+5e6t7obJaltBHGjHoVKrB2Kr8y2fM8T6tVdqrkh4kH0d+T8AGPKnlHrnqGXrAqHbIxlsHSw/eeNNNSccFby04tyB1BRu1YF2TslpdIDY56ODsLdXLW4ENwubw6SWyR4ynMjTZwFtQd1SGxfMaz/ugK4kAy6AvPT8UEKLk7KNu9FxmIlqpPUGR6WbKxtmNIixkrCreiIBVK8aflCBEtFsMKjHuPp0ujinttxRrR7mq9vRcqHP2Ur9P1Lkt92rMxsbzrN9C5GQ5tPeGKn+CizmOjvpl5imxs4b8AghChQKUdtkXwi1fAeua6hbaetKOWG+ZF2YSoTjdTHn76IlhUNmYwkgb7YUerFme+QIkqrlZ5VBYBmBWEaKsY1+3NJeljPhYrZzNznJwkYKgOv0OK0kAhiHzmoKs1N1jZK9faSIfDXpcpFtcqmwZAMvo3Me7QwApZmY1k9BOHK5xLMOACYBlpCOIaxAWGAG7wJOdEPSafC3JxE/yre/ZfkGhCoSaoEDejCD6buSNT2/zlsVcC7HY4k5Kmh5BoVOVvWMjD1PUQA8lmNu//zj5SlJhBWEQSI8mpjpRvr3rIrt/x7SKXe6nbXj4RlL7BpUnavhmx7uDQNdEgqZZjSzUgz38iF62N86U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
