travis:
  secure:
    BINSTAR_TOKEN: Bp2c69fZztsEbIFPvpY0BlO9JxZZonG8ow7ZTrfZvZ2FHL+DuTAAIe06BPei8JJeli360ZaoBtgFtoMUX6UI3RiY3KEyJU9azv8maw5/+K2RxOGeb8l2Lob3VH1w5wcmlV3JuxYkf/y42XvELG7daG4oN+ahcjTpD7lTR9Z+eppLzXEMw8x/uyN924S4GGcDq5QHpoxml8D1BpD63MvAvygIUarMm+YKeq8tOUlokZd5SPLRfcze5+8RyE555ZcjirBx0oQA9ovFPzIkv9BBXp6MO89za1H4vcobs4U4ZgkEh8tnp6BVogg5TAMdzO8s+tDOM0fIjuGObmNT8ErP5pYSbWiCWeaGSqUu11EhbWoEjyCtkxVyRp2dDsix2jPx/zX7/YOGr5k8IN1tiy1IgG2q++RX7BN/o4KU8LT4K34upHxa09sVk2pBNfF7pRKxEXkFrClIixUJcI2QiceOOfgSgXKVNI1gogY3w7aQS+5zWQVWSrm8wqzLXJlOWLA0XRU8jI5fBEJa+b+EVVXYzTBUKPz/cDeq4Oy9Qrs+usjJWNFHfoIDFtbeqqlQg+s8jBkxAFHNTxhSGzB0EZ00TqgyUBQdcVCIQYtrMoGqRSFVBnIyAEjS/2Iy9YRtCi4FiKSYH0eNy3y7kGZ5u7o3B97I1N60z+PronmTRFt1oL4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
